name: Playwright Tests (Debug)
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: System Information
      run: |
        echo "OS: $(uname -a)"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Available memory: $(free -h)"
        echo "Disk space: $(df -h)"
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: Validate environment
      run: |
        echo "USERNAME: ${USERNAME:+Set}"
        echo "PASSWORD: ${PASSWORD:+Set}"
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
    
    - name: Run Playwright tests
      run: npx playwright test --reporter=html,line
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        CI: true
        DEBUG: pw:api
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          
    - name: Upload videos and screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-artifacts
        path: |
          test-results/